apiVersion: v1
kind: Pod
metadata:
  name: mnist-training
spec:
  restartPolicy: OnFailure
  containers:
    - name: mnist-training
      image: 172.30.1.1:5000/mnist/mnist-training:latest
      imagePullPolicy: Always
# this code is for Using GPU
#      env:
#        - name: NVIDIA_VISIBLE_DEVICES
#          value: all
#        - name: NVIDIA_DRIVER_CAPABILITIES
#          value: "compute,utility"
#        - name: NVIDIA_REQUIRE_CUDA  
#          value: "cuda>=5.0"
#      securityContext:
#        allowPrivilegeEscalation: false
#        capabilities:
#          drop: ["ALL"]
#        seLinuxOptions:
#          type: nvidia_container_t
#      resources:
#        limits:
#          nvidia.com/gpu: 1 # requesting 1 GPU
