apiVersion: v1
kind: DeploymentConfig
metadata:
  name: mnist-serving
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mnist-serving
    spec:
      containers:
      - name: mnist-serving-server
        imagePullPolicy: Always
        image: 172.30.1.1:5000/mnist/mnist-serving:latest
        ports:
        - containerPort: 8500
        command:
        - bash
        - -c
        - tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=mnist --model_base_path=/app/mnist;
        restartPolicy: Always
      - name: mnist-serving-client
        image: 172.30.1.1:5000/mnist/mnist-serving:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        command:
        - bash
        - -c
        - python /app/mnist_client_rest_rpc.py --server=localhost:8500 --concurrency=100
        restartPolicy: Always
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - mnist-serving-client
      from:
        kind: ImageStream
        name: mnist-serving:latest
    type: ImageChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - mnist-serving-server
      from:
        kind: ImageStream
        name: mnist-serving:latest
    type: ImageChange
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mnist-serving
  name: mnist-serving
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: mnist-serving
  type: ClusterIP
